### ISSUE TITLE
STL Part Rotation

### ISSUE THREAD

**Issue by ghost** [exiii/HACKberry#3]
When importing individual STL parts into CAD and 3D software, certain parts are rotated inconsistently.

![part-rotation-01](https://cloud.githubusercontent.com/assets/2131950/10932040/0b61589a-8282-11e5-95c0-509105dc1f15.png)
![part-rotation-02](https://cloud.githubusercontent.com/assets/2131950/10932039/0b5ec09e-8282-11e5-9f52-2d4c66f5ee03.png)
![part-rotation-03](https://cloud.githubusercontent.com/assets/2131950/10932150/2add8558-8283-11e5-85ad-711e96117c9f.png)

What's the easiest way to ensure the STL files have consistent rotation and alignment?

**Comment by yamaulab** [comment]
hi,
if you want to know correct positions of parts,
please download .stp or .x_t file from github and open it using CAD(such as
fusion 360).
Maybe you can also translate the assembly file into .stl.

**Comment by ghost** [comment]
> Maybe you can also translate the assembly file into .stl.

What file is the assembly file? I've translated the STP into STL, but it loses quality when I import it into the 3D modelling software.

> if you want to know correct positions of parts, please download .stp or .x_t file from github and open it using CAD(such as fusion 360).

I thought that someone who worked on the project might be able to see a pattern to the files with inconsistent rotation and rotate them. Either that, or be able to recreate the STL files (from the assembly file?) with consistent orientation.

I've already tried rotating the parts manually, but it has taken over an hour to do just a few parts and I'm still not sure if I have them in the correct position and alignment.

**Comment by yamaulab** [comment]
> What file is the assembly file?
> These files are assembly files.
> https://github.com/exiii/HACKberry/blob/master/HACKberry-hardware/3D/HACKberry_v1.stp
> https://github.com/exiii/HACKberry/blob/master/HACKberry-hardware/3D/HACKberry_v1.x_t

I just updated these files.
My FreeCAD(windows 8.1 64-bit version 0.15) could open STEP file successfully.
It could also generate STL file.

![](http://i.imgur.com/y4oi8qel.png)
![](http://i.imgur.com/eT7iykel.png)

For further questions,
Please feel free to post to our forum.
http://exiii-hackberry.com/forum_top/
